version: 2.3.{build}
image: Visual Studio 2019


platform:
    - Any CPU

configuration:
    - Release
    - Debug


install:
    #empty dummy file, not available at github due to passwords in it
    - echo //dummy  > %APPVEYOR_BUILD_FOLDER%\JenkinsTest\FuncUnitTests.cs

    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\JenkinsTest\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\JenkinsWebApiFwk45\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages
        
    - ps: >-
        Start-FileDownload 'https://github.com/EWSoftware/SHFB/releases/download/v2020.3.6.0/SHFBInstaller_v2020.3.6.0.zip'

        7z x -y SHFBInstaller_v2020.3.6.0.zip | Out-Null

        Write-Host "Installing MSI..."

        cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet

        Write-Host "Installing VSIX..."

        . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2017AndLater.vsix

        Write-Host "Sandcastle installed" -ForegroundColor Green

    - set SHFBROOT=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild JenkinsWebApi.sln /m /verbosity:minimal /t:restore /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild JenkinsWebApi.sln /m /verbosity:minimal /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cd "%APPVEYOR_BUILD_FOLDER%"\Nuget
    - if "%configuration%"=="Release" pack.cmd

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        if ($env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "Nuget\JenkinsWebApi.2.3.0.nupkg" -FileName JenkinsWebApi.2.3.0.nupkg
        }
        
        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "Nuget\JenkinsWebApi.2.3.0.nupkg" -FileName JenkinsWebApi.2.3.0.nupkg
        }

artifacts:
  - path: Nuget\JenkinsWebApi_*.nupkg
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        configuration: Release
