name: Continuous Integration 2022

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release, Debug]
    env:
      Solution: JenkinsWebApi.sln
      NugetSpc: JenkinsWebApi.nuspec

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Show VS Version
      run: |
           "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property displayName
           "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productDisplayVersion
      shell: cmd

    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v1

    - name: Copy dummy key for signing
      run: |
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApi90\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApi80\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApi70\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApi60\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApi50\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiCore20\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiCore21\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiCore30\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiCore31\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiFwk45\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiFwk48\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiStd20\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiStd21\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\JenkinsWebApiUwp\Bassman.snk

    - name: Nuget restore solution
      run: nuget restore $env:Solution

    - name: MSBuild of solution
      run: msbuild $env:Solution /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal

#    - name: Nuget pack nuspec
#      if: matrix.build_configuration == 'Release'
#      working-directory: .\Nuget\
#      run: nuget pack $env:NugetSpc -properties Configuration="${{ matrix.build_configuration }}"